version: "3.9"
services:
  app0:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: app0
    command: ["./main"]
    ports:
      - "50000:50000" # Expose the port for this node
    environment:
      - NODE_ID=0
      - PEERS=0,1,2,3,4

  app1:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: app1
    command: ["./main"]
    ports:
      - "50001:50001"
    environment:
      - NODE_ID=1
      - PEERS=0,1,2,3,4

  app2:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: app2
    command: ["./main"]
    ports:
      - "50002:50002"
    environment:
      - NODE_ID=2
      - PEERS=0,1,2,3,4

  app3:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: app3
    command: ["./main"]
    ports:
      - "50003:50003"
    environment:
      - NODE_ID=3
      - PEERS=0,1,2,3,4

  app4:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: app4
    command: ["./main"]
    ports:
      - "50004:50004"
    environment:
      - NODE_ID=4
      - PEERS=0,1,2,3,4

  client0:
    build:
      context: ./client
      dockerfile: ./Dockerfile.client # Use the new Dockerfile for the client
    stdin_open: true # Keeps stdin open
    tty: true # Allocates a pseudo-TTY
    container_name: client0
    command: ["./client"] # Run the client binary
    environment:
      - NAME=Carina
      - CLIENT_ID=0
    depends_on: # Ensure the client waits for the cluster to start
      - app0
      - app1
      - app2
      - app3
      - app4
    volumes:
      - ./logs:/app/logs

  client1:
    build:
      context: ./client
      dockerfile: ./Dockerfile.client # Use the new Dockerfile for the client
    stdin_open: true # Keeps stdin open
    tty: true # Allocates a pseudo-TTY
    container_name: client1
    command: ["./client"] # Run the client binary
    environment:
      - NAME=JK
      - CLIENT_ID=1
    depends_on: # Ensure the client waits for the cluster to start
      - app0
      - app1
      - app2
      - app3
      - app4
    volumes:
      - ./logs:/app/logs
