version: '3'
services:
  app1:
    build: .
    container_name: app1
    ports:
      - "8081:8080"
  app2:
    build: .
    container_name: app2
    ports:
      - "8082:8080"
  app3:
    build: .
    container_name: app3
    ports:
      - "8083:8080"
  app4:
    build: .
    container_name: app4
    ports:
      - "8084:8080"
  app5:
    build: .
    container_name: app5
    ports:
      - "8085:8080"
