version: '3'
services:
  app0:
    build:
      context: ./client
      dockerfile: ClientDockerfile
    container_name: app1
    ports:
      - "8081:8080"
    stdin_open: true
  app1:
    build:
      context: ./client
      dockerfile: ClientDockerfile
    container_name: app2
    ports:
      - "8082:8080"
    stdin_open: true
  app2:
    build:
      context: ./server
      dockerfile: ServerDockerfile
    container_name: app3
    ports:
      - "8083:8080"