version: '3'
services:
  app1:
    build: .
    ports:
      - "8081:8080"
  app2:
    build: .
    ports:
      - "8082:8080"
  app3:
    build: .
    ports:
      - "8083:8080"
  app4:
    build: .
    ports:
      - "8084:8080"
  app5:
    build: .
    ports:
      - "8085:8080"
