
# Use a lightweight base image with Go installed
FROM golang:1.23.2

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules and download dependencies
COPY go.mod  ./
RUN go mod download

# Copy the entire application code
COPY . .
RUN touch /app/example.txt


# Build the Go application, for faster compilation
RUN go build -o main . 

# Set the command to run the application
CMD ["./main"]